export const tagPattern = /^[a-z0-9]+(-[a-z0-9]+)*$/

export const aliases = {
    'c++': 'cpp',
    'c#': 'csharp',
    'f#': 'fsharp',
    '.net': 'dotnet',
    'asp.net': 'aspnet',
    js: 'javascript',
    ts: 'typescript',
    reactjs: 'react',
    'react.js': 'react',
    'react-js': 'react',
    'react native': 'react-native',
    reactnative: 'react-native',
    vuejs: 'vue',
    'vue.js': 'vue',
    'vue-js': 'vue',
    'next.js': 'nextjs',
    next: 'nextjs',
    'nuxt.js': 'nuxt',
    nuxtjs: 'nuxt',
    'node.js': 'node',
    nodejs: 'node',
    'node-js': 'node',
    'express.js': 'express',
    expressjs: 'express',
    'nest.js': 'nestjs',
    nest: 'nestjs',
    'svelte.js': 'svelte',
    sveltejs: 'svelte',
    'angular.js': 'angularjs',
    golang: 'go',
    py: 'python',
    postgresql: 'postgres',
    mongo: 'mongodb',
    k8s: 'kubernetes',
    tailwindcss: 'tailwind',
    'tailwind-css': 'tailwind',
    'three.js': 'threejs',
    ml: 'machine-learning',
    ai: 'artificial-intelligence',
    'gen-ai': 'generative-ai',
    genai: 'generative-ai',
    llm: 'llms',
    ux: 'ui-ux',
    ui: 'ui-ux',
    'ui/ux': 'ui-ux',
    amazon: 'aws',
    gcp: 'google-cloud',
    'google cloud': 'google-cloud',
}

export const starterTags = [
    'javascript',
    'typescript',
    'python',
    'java',
    'go',
    'rust',
    'cpp',
    'csharp',
    'php',
    'ruby',
    'kotlin',
    'swift',
    'dart',
    'react',
    'nextjs',
    'vue',
    'nuxt',
    'angular',
    'svelte',
    'astro',
    'tailwind',
    'node',
    'express',
    'nestjs',
    'django',
    'flask',
    'fastapi',
    'spring',
    'laravel',
    'rails',
    'dotnet',
    'react-native',
    'flutter',
    'android',
    'ios',
    'postgres',
    'mysql',
    'mongodb',
    'redis',
    'graphql',
    'docker',
    'kubernetes',
    'aws',
    'google-cloud',
    'azure',
    'linux',
    'machine-learning',
    'generative-ai',
    'llms',
    'data-science',
    'ui-ux',
    'open-source',
    'web3',
    'game-dev',
    'threejs',
]

const clean = (value) =>
    value
        .toLowerCase()
        .replace(/[\s_/.]+/g, '-')
        .replace(/[^a-z0-9-]/g, '')
        .replace(/-+/g, '-')
        .replace(/^-|-$/g, '')

export const normalizeTag = (value) => {
    const raw = String(value).trim().toLowerCase()
    if (aliases[raw]) return aliases[raw]
    const cleaned = clean(raw)
    return aliases[cleaned] ?? cleaned
}
